- hosts: all
  become: yes
  gather_facts: false
  tasks:
  - name: Install docker packages
    remote_user: ansadmin
    apt:
      name: ['apt-transport-https','ca-certificates', 'curl', 'software-properties-common']
      state: present
      update_cache: yes
    tags:
      - docker
  - name: Add Docker s GPG key for ubuntu from official site
    remote_user: ansadmin
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    tags:
      - docker
  - name: Verify gpg key with the fingerprint
    remote_user: ansadmin
    apt_key:
      id: 0EBFCD88
      state: present
    tags:
      - docker
  - name: Configure Docker for ubuntu stable repository
    remote_user: ansadmin
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
      update_cache: yes
    tags:
      - docker
  - name: Update apt packages
    remote_user: ansadmin
    apt:
      update_cache: yes
    tags:
      - docker
  - name: Install docker-ce
    remote_user: ansadmin
    apt:
      name: docker-ce
      state: present
      update_cache: yes
    tags:
      - docker
  - name: Add "ansadmin" user to "docker" group
    remote_user: ansadmin
    user:
      name: "ansadmin"
      groups: "docker"
      append: yes
    tags:
      - docker
  - name: Install docker-compose
    remote_user: ansadmin
    get_url: 
      url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x,o+x'